export const colorTypes = [
  { name: "bug", color: "#94BC4A" },
  { name: "dark", color: "#736C75" },
  { name: "dragon", color: "#6A7BAF" },
  { name: "electric", color: "#E5C531" },
  { name: "fairy", color: "#E397D1" },
  { name: "fighting", color: "#CB5F48" },
  { name: "fire", color: "#EA7A3C" },
  { name: "flying", color: "#7DA6DE" },
  { name: "ghost", color: "#846AB6" },
  { name: "grass", color: "#71C558" },
  { name: "ground", color: "#CC9F4F" },
  { name: "ice", color: "#70CBD4" },
  { name: "poison", color: "#B468B7" },
  { name: "psychic", color: "#E5709B" },
  { name: "rock", color: "#B2A061" },
  { name: "steel", color: "#89A1B0" },
  { name: "water", color: "#539AE2" },
];
